# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatars',
            old_name='userid',
            new_name='user',
        ),
    ]
