# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_userid', models.IntegerField()),
                ('to_userid', models.IntegerField()),
                ('message', models.CharField(max_length=4000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
