Insert into TAGS (TAGID,NAME) values (1,'Security');
Insert into TAGS (TAGID,NAME) values (2,'Genetics');
Insert into TAGS (TAGID,NAME) values (3,'Machine Learning');
Insert into TAGS (TAGID,NAME) values (4,'Antivirus');
Insert into TAGS (TAGID,NAME) values (5,'Internet');
Insert into TAGS (TAGID,NAME) values (6,'Web Technologies');
Insert into TAGS (TAGID,NAME) values (7,'Databases');
Insert into TAGS (TAGID,NAME) values (8,'Scripting');
Insert into TAGS (TAGID,NAME) values (9,'BackEnd');
Insert into TAGS (TAGID,NAME) values (10,'FrontEnd');
INSERT INTO tags (tagId,name) VALUES (11,'Artificial Intelligence');
INSERT INTO tags (tagId,name) VALUES (12,'Computation and Language');
INSERT INTO tags (tagId,name) VALUES (13,'Computational Complexity');
INSERT INTO tags (tagId,name) VALUES (14,'Computational Engineering, Finance, and Science');
INSERT INTO tags (tagId,name) VALUES (15,'Computational Geometry');
INSERT INTO tags (tagId,name) VALUES (16,'Computer Science and Game Theory');
INSERT INTO tags (tagId,name) VALUES (17,'Computer Vision and Pattern Recognition');
INSERT INTO tags (tagId,name) VALUES (18,'Computers and Society');
INSERT INTO tags (tagId,name) VALUES (19,'Cryptography and Security');
INSERT INTO tags (tagId,name) VALUES (20,'Data Structures and Algorithms');
INSERT INTO tags (tagId,name) VALUES (21,'Databases');
INSERT INTO tags (tagId,name) VALUES (22,'Digital Libraries');
INSERT INTO tags (tagId,name) VALUES (23,'Discrete Mathematics');
INSERT INTO tags (tagId,name) VALUES (24,'Distributed, Parallel, and Cluster Computing');
INSERT INTO tags (tagId,name) VALUES (25,'Emerging Technologies');
INSERT INTO tags (tagId,name) VALUES (26,'Formal Languages and Automata Theory');
INSERT INTO tags (tagId,name) VALUES (27,'General Literature');
INSERT INTO tags (tagId,name) VALUES (28,'Graphics');
INSERT INTO tags (tagId,name) VALUES (29,'Hardware Architecture');
INSERT INTO tags (tagId,name) VALUES (30,'Human-Computer Interaction');
INSERT INTO tags (tagId,name) VALUES (31,'Information Retrieval');
INSERT INTO tags (tagId,name) VALUES (32,'Information Theory');
INSERT INTO tags (tagId,name) VALUES (33,'Learning');
INSERT INTO tags (tagId,name) VALUES (34,'Logic in Computer Science');
INSERT INTO tags (tagId,name) VALUES (35,'Mathematical Software');
INSERT INTO tags (tagId,name) VALUES (36,'Multiagent Systems');
INSERT INTO tags (tagId,name) VALUES (37,'Multimedia');
INSERT INTO tags (tagId,name) VALUES (38,'Networking and Internet Architecture');
INSERT INTO tags (tagId,name) VALUES (39,'Neural and Evolutionary Computing');
INSERT INTO tags (tagId,name) VALUES (40,'Numerical Analysis');
INSERT INTO tags (tagId,name) VALUES (41,'Operating Systems');
INSERT INTO tags (tagId,name) VALUES (42,'Other Computer Science');
INSERT INTO tags (tagId,name) VALUES (43,'Performance');
INSERT INTO tags (tagId,name) VALUES (44,'Programming Languages');
INSERT INTO tags (tagId,name) VALUES (45,'Robotics');
INSERT INTO tags (tagId,name) VALUES (46,'Social and Information Networks');
INSERT INTO tags (tagId,name) VALUES (47,'Software Engineering');
INSERT INTO tags (tagId,name) VALUES (48,'Sound');
INSERT INTO tags (tagId,name) VALUES (49,'Symbolic Computation');
INSERT INTO tags (tagId,name) VALUES (50,'Systems and Control');
INSERT INTO tags (tagId,name) VALUES (51,'Computer Science');
