INSERT INTO resources (resourceId,name,URI) VALUES (6,'Artificial Intelligence','https://arxiv.org/list/cs.AI/new');
INSERT INTO resources (resourceId,name,URI) VALUES (7,'Computation and Language','https://arxiv.org/list/cs.CL/new');
INSERT INTO resources (resourceId,name,URI) VALUES (8,'Computational Complexity','https://arxiv.org/list/cs.CC/new');
INSERT INTO resources (resourceId,name,URI) VALUES (9,'Computational Engineering, Finance, and Science','https://arxiv.org/list/cs.CE/new');
INSERT INTO resources (resourceId,name,URI) VALUES (10,'Computational Geometry','https://arxiv.org/list/cs.CG/new');
INSERT INTO resources (resourceId,name,URI) VALUES (11,'Computer Science and Game Theory','https://arxiv.org/list/cs.GT/new');
INSERT INTO resources (resourceId,name,URI) VALUES (12,'Computer Vision and Pattern Recognition','https://arxiv.org/list/cs.CV/new');
INSERT INTO resources (resourceId,name,URI) VALUES (13,'Computers and Society','https://arxiv.org/list/cs.CY/new');
INSERT INTO resources (resourceId,name,URI) VALUES (14,'Cryptography and Security','https://arxiv.org/list/cs.CR/new');
INSERT INTO resources (resourceId,name,URI) VALUES (15,'Data Structures and Algorithms','https://arxiv.org/list/cs.DS/new');
INSERT INTO resources (resourceId,name,URI) VALUES (16,'Databases','https://arxiv.org/list/cs.DB/new');
INSERT INTO resources (resourceId,name,URI) VALUES (17,'Digital Libraries','https://arxiv.org/list/cs.DL/new');
INSERT INTO resources (resourceId,name,URI) VALUES (18,'Discrete Mathematics','https://arxiv.org/list/cs.DM/new');
INSERT INTO resources (resourceId,name,URI) VALUES (19,'Distributed, Parallel, and Cluster Computing','https://arxiv.org/list/cs.DC/new');
INSERT INTO resources (resourceId,name,URI) VALUES (20,'Emerging Technologies','https://arxiv.org/list/cs.ET/new');
INSERT INTO resources (resourceId,name,URI) VALUES (21,'Formal Languages and Automata Theory','https://arxiv.org/list/cs.FL/new');
INSERT INTO resources (resourceId,name,URI) VALUES (22,'General Literature','https://arxiv.org/list/cs.GL/new');
INSERT INTO resources (resourceId,name,URI) VALUES (23,'Graphics','https://arxiv.org/list/cs.GR/new');
INSERT INTO resources (resourceId,name,URI) VALUES (24,'Hardware Architecture','https://arxiv.org/list/cs.AR/new');
INSERT INTO resources (resourceId,name,URI) VALUES (25,'Human-Computer Interaction','https://arxiv.org/list/cs.HC/new');
INSERT INTO resources (resourceId,name,URI) VALUES (26,'Information Retrieval','https://arxiv.org/list/cs.IR/new');
INSERT INTO resources (resourceId,name,URI) VALUES (27,'Information Theory','https://arxiv.org/list/cs.IT/new');
INSERT INTO resources (resourceId,name,URI) VALUES (28,'Learning','https://arxiv.org/list/cs.LG/new');
INSERT INTO resources (resourceId,name,URI) VALUES (29,'Logic in Computer Science','https://arxiv.org/list/cs.LO/new');
INSERT INTO resources (resourceId,name,URI) VALUES (30,'Mathematical Software','https://arxiv.org/list/cs.MS/new');
INSERT INTO resources (resourceId,name,URI) VALUES (31,'Multiagent Systems','https://arxiv.org/list/cs.MA/new');
INSERT INTO resources (resourceId,name,URI) VALUES (32,'Multimedia','https://arxiv.org/list/cs.MM/new');
INSERT INTO resources (resourceId,name,URI) VALUES (33,'Networking and Internet Architecture','https://arxiv.org/list/cs.NI/new');
INSERT INTO resources (resourceId,name,URI) VALUES (34,'Neural and Evolutionary Computing','https://arxiv.org/list/cs.NE/new');
INSERT INTO resources (resourceId,name,URI) VALUES (35,'Numerical Analysis','https://arxiv.org/list/cs.NA/new');
INSERT INTO resources (resourceId,name,URI) VALUES (36,'Operating Systems','https://arxiv.org/list/cs.OS/new');
INSERT INTO resources (resourceId,name,URI) VALUES (37,'Other Computer Science','https://arxiv.org/list/cs.OH/new');
INSERT INTO resources (resourceId,name,URI) VALUES (38,'Performance','https://arxiv.org/list/cs.PF/new');
INSERT INTO resources (resourceId,name,URI) VALUES (39,'Programming Languages','https://arxiv.org/list/cs.PL/new');
INSERT INTO resources (resourceId,name,URI) VALUES (40,'Robotics','https://arxiv.org/list/cs.RO/new');
INSERT INTO resources (resourceId,name,URI) VALUES (41,'Social and Information Networks','https://arxiv.org/list/cs.SI/new');
INSERT INTO resources (resourceId,name,URI) VALUES (42,'Software Engineering','https://arxiv.org/list/cs.SE/new');
INSERT INTO resources (resourceId,name,URI) VALUES (43,'Sound','https://arxiv.org/list/cs.SD/new');
INSERT INTO resources (resourceId,name,URI) VALUES (44,'Symbolic Computation','https://arxiv.org/list/cs.SC/new');
INSERT INTO resources (resourceId,name,URI) VALUES (45,'Systems and Control','https://arxiv.org/list/cs.SY/new');
